---
- name: Update web servers
  hosts: UBU

  tasks:

  #make sure to do apt-get update inorder to install pip3 first time other it will not got through
  #this script only runs on UBUNTU Ubuntu Server 20.04 LTS (HVM), SSD Volume Type - ami-00399ec92321828f5 (64-bit x86) / ami-08e6b682a466887dd (64-bit Arm)
  - name: Update apt repo and cache on all Debian/Ubuntu boxes
    apt: update_cache=yes force_apt_get=yes cache_valid_time=3600

  - name: Ensure python3 present
    ansible.builtin.apt:
      name: python3

  - name: Ensure pip present
    ansible.builtin.apt:
      name: python3-pip

  - name: Transfer the preperation script
    copy: src=../scripts/prepare-airflow-env.sh dest=/home mode=0777

  - name: Transfer the lauch script
    copy: src=../scripts/launch-airflow.sh dest=/home mode=0777      

  #- name: Transfer the create user script
  #  copy: src=../scripts/create-user.sh dest=/home mode=0777     

  - name: Execute the preperation script
    command: sh /home/prepare-airflow-env.sh

  - name: Execute the lauch script
    command: sh /home/launch-airflow.sh

  # - name: Execute the create-user script
  #  command: sh /home/create-user.sh  
  
